[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 10_000
via-ir = true
evm_version = "cancun"
gas_reports = ["*"]
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read-write", path = "./frontend/public/deployments" }
]

[profile.ci]
via-ir = true
gas_reports = []

[fuzz]
runs = 128

[invariant]
runs = 32
depth = 64
fail_on_revert = false
